### ISSUE TITLE
missing or invalid statistic

### ISSUE THREAD

**Issue by TSERATO** [Artemis-the-gr8/PlayerStatsExpansion#46]
Hello,
Im getting this issue in my console, where very few seconds this shows up:
`WARN
16:31:20

[PlayerStatsExpansion]: missing or invalid statistic

INFO
16:31:52

[PlayerStatsExpansion]: clearing stored messages...`
Ive tried everything, like reinstalling the plugin and extention. 
Any advice?
Thank you,
Alex!

**Comment by Artemis-the-gr8** [comment]
That sounds like you have a placeholder somewhere that isn't formatted properly: specifically one without a statistic, or with a misspelled statistic. Are you using placeholders in a leaderboard or hologram or something of the sort?

Reinstalling the plugin and extension wouldn't fix this issue if that is the case, because the extension will just load the same placeholder again whenever it's installed - you'll have to find the non-functioning placeholder.
